<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>havenkare-hms</title>

    <!-- Tailwind CSS generated by CLI -->
    <link rel="stylesheet" href="./assets/css/output.css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="./assets/css/tailwind.css">
</head>

<body>
    <!-- Navbar starts from here -->
    <nav id="Navbar" class="bg-base-100 shadow-sm">
        <div class="navbar w-5/6 mx-auto">
            <div class="navbar-start">
                <div class="dropdown">
                    <div tabindex="0" role="button" class="btn btn-ghost lg:hidden">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M4 6h16M4 12h8m-8 6h16" />
                        </svg>
                    </div>
                    <ul tabindex="-1"
                        class="menu menu-sm dropdown-content bg-base-100 rounded-box z-1 mt-3 w-52 p-2 shadow navbar-menus">
                        <li><a href="#">Home</a></li>
                        <li><a href="#">Services</a></li>
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Gallery</a></li>
                        <li><a href="#">Contact Us</a></li>
                        <li><a href="#">Logins</a></li>
                    </ul>
                </div>
                <a class="text-xl">
                    <img src="./assets/images/logo.png" alt="HeavenKare Logo" class="w-25">
                </a>
            </div>
            <div class="navbar-center hidden lg:flex">
                <ul class="menu menu-horizontal px-1 navbar-menus">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Services</a></li>
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Gallery</a></li>
                    <li><a href="#">Contact Us</a></li>
                    <li><a href="#">Logins</a></li>
                </ul>
            </div>
            <div class="navbar-end">
                <a class="btn">Book an Appointment</a>
            </div>
        </div>
    </nav>
</body>

</html>
