<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>havenkare-hms</title>

    <!-- Font awesome link -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" />

    <!-- Tailwind CSS generated by CLI -->
    <link rel="stylesheet" href="./assets/css/output.css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="./assets/css/tailwind.css">
</head>

<body>
    <!-- Navbar starts from here -->
    <nav id="Navbar" class="shadow-sm sticky top-0 bg-white z-10">
        <div class="navbar w-5/6 mx-auto">
            <div class="navbar-start">
                <div class="dropdown">
                    <div tabindex="0" role="button" class="btn btn-ghost lg:hidden">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M4 6h16M4 12h8m-8 6h16" />
                        </svg>
                    </div>
                    <ul tabindex="-1"
                        class="menu menu-sm dropdown-content bg-base-100 rounded-box z-1 mt-3 w-52 p-2 shadow navbar-menus">
                        <li><a href="#">Home</a></li>
                        <li><a href="#">Services</a></li>
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Gallery</a></li>
                        <li><a href="#">Contact Us</a></li>
                        <li><a href="#">Logins</a></li>
                    </ul>
                </div>
                <a class="text-xl">
                    <img src="./assets/images/logo.png" alt="HeavenKare Logo" class="w-25">
                </a>
            </div>
            <div class="navbar-center hidden lg:flex">
                <ul class="menu menu-horizontal px-1 navbar-menus">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Services</a></li>
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Gallery</a></li>
                    <li><a href="#">Contact Us</a></li>
                    <li><a href="#">Logins</a></li>
                </ul>
            </div>
            <div class="navbar-end">
                <a class="btn">Book an Appointment</a>
            </div>
        </div>
    </nav>

    <!-- Carousel starts from here  -->
    <div class="carousel w-full">
        <div id="slide1" class="carousel-item relative w-full">
            <img src="./assets/images/carousel1.jpg" class="w-full h-[460px] object-cover" />
            <div class="absolute left-5 right-5 top-1/2 flex -translate-y-1/2 transform justify-between">
                <a href="#slide3" class="btn btn-circle">❮</a>
                <a href="#slide2" class="btn btn-circle">❯</a>
            </div>
        </div>
        <div id="slide2" class="carousel-item relative w-full">
            <img src="./assets/images/carousel2.jpeg" class="w-full h-[460px] object-cover" />
            <div class="absolute left-5 right-5 top-1/2 flex -translate-y-1/2 transform justify-between">
                <a href="#slide1" class="btn btn-circle">❮</a>
                <a href="#slide3" class="btn btn-circle">❯</a>
            </div>
        </div>
        <div id="slide3" class="carousel-item relative w-full">
            <img src="./assets/images/carousel3.jpg" class="w-full h-[460px] object-cover" />
            <div class="absolute left-5 right-5 top-1/2 flex -translate-y-1/2 transform justify-between">
                <a href="#slide2" class="btn btn-circle">❮</a>
                <a href="#slide1" class="btn btn-circle">❯</a>
            </div>
        </div>
    </div>

    <!-- Logins starts from here -->
    <section id="login-section" class="py-24 bg-[#f9f9f9]">
        <!-- Section Heading -->
        <div class="text-center mb-10">
            <h2 class="text-3xl font-bold text-gray-800">Logins</h2>
            <p class="text-gray-600">Select your login portal</p>
        </div>

        <!-- Login Cards Grid -->
        <div class="grid grid-cols-1 md:grid-cols-3 gap-10 justify-items-center w-9/12 mx-auto">

            <!-- Patient Login Card -->
            <div
                class="card w-80 bg-white shadow-md hover:shadow-lg transition-all duration-300 rounded-2xl border border-gray-200">
                <figure class="overflow-hidden rounded-t-2xl">
                    <img src="./assets/images/patient.jpg" alt="Patient Login"
                        class="w-full h-52 object-cover hover:scale-105 transition-transform duration-500" />
                </figure>
                <div class="card-body items-center text-center">
                    <h2 class="card-title text-lg font-semibold text-gray-800">
                        Patient Login
                    </h2>
                    <p class="text-sm text-gray-500 mb-3">
                        Access your health records and appointments.
                    </p>

                    <a href="#" class="btn btn-neutral btn-xs sm:btn-sm md:btn-md lg:btn-lg rounded-xl w-full">
                        Click Here
                    </a>
                </div>
            </div>

            <!-- Doctor Login Card -->
            <div
                class="card w-80 bg-white shadow-md hover:shadow-lg transition-all duration-300 rounded-2xl border border-gray-200">
                <figure class="overflow-hidden rounded-t-2xl">
                    <img src="./assets/images/doctor.jpg" alt="Doctor Login"
                        class="w-full h-52 object-cover hover:scale-105 transition-transform duration-500" />
                </figure>
                <div class="card-body items-center text-center">
                    <h2 class="card-title text-lg font-semibold text-gray-800">
                        Doctor Login
                    </h2>
                    <p class="text-sm text-gray-500 mb-3">
                        Manage appointments and patient information securely.
                    </p>

                    <a href="#" class="btn btn-neutral btn-xs sm:btn-sm md:btn-md lg:btn-lg rounded-xl w-full">
                        Click Here
                    </a>
                </div>
            </div>

            <!-- Admin Login Card -->
            <div
                class="card w-80 bg-white shadow-md hover:shadow-lg transition-all duration-300 rounded-2xl border border-gray-200">
                <figure class="overflow-hidden rounded-t-2xl">
                    <img src="./assets/images/admin.jpeg" alt="Admin Login"
                        class="w-full h-52 object-cover hover:scale-105 transition-transform duration-500" />
                </figure>
                <div class="card-body items-center text-center">
                    <h2 class="card-title text-lg font-semibold text-gray-800">
                        Admin Login
                    </h2>
                    <p class="text-sm text-gray-500 mb-3">
                        Access and control system settings and user data.
                    </p>
                    <a href="#" class="btn btn-neutral btn-xs sm:btn-sm md:btn-md lg:btn-lg rounded-xl w-full">
                        Click Here
                    </a>
                </div>
            </div>

        </div>
    </section>

    <!-- Features starts from here -->
    <section id="features" class="py-16">
        <div class="max-w-7xl mx-auto px-6 text-center">
            <!-- Section Title -->
            <div class="mb-12">
                <h2 class="text-3xl md:text-4xl font-bold text-gray-800 mb-3">
                    Our Key Features
                </h2>
                <p class="text-gray-600">
                    Take a look at some of our key features
                </p>
            </div>

            <!-- Features Grid -->
            <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
                <!-- Single Feature -->
                <div
                    class="group bg-gray-50 hover:bg-white rounded-2xl shadow-md hover:shadow-xl transition-all p-8 border border-transparent hover:border-gray-200 cursor-pointer">
                    <div class="text-5xl mb-4 group-hover:scale-110 transition-transform duration-300">
                        <i class="fas fa-heartbeat"></i>
                    </div>
                    <h5 class="text-xl font-semibold text-gray-800">Cardiology</h5>
                </div>

                <div
                    class="group bg-gray-50 hover:bg-white rounded-2xl shadow-md hover:shadow-xl transition-all p-8 border border-transparent hover:border-gray-200 cursor-pointer">
                    <div class="text-5xl mb-4 group-hover:scale-110 transition-transform duration-300">
                        <i class="fas fa-ribbon"></i>
                    </div>
                    <h5 class="text-xl font-semibold text-gray-800">Orthopaedic</h5>
                </div>

                <div
                    class="group bg-gray-50 hover:bg-white rounded-2xl shadow-md hover:shadow-xl transition-all p-8 border border-transparent hover:border-gray-200 cursor-pointer">
                    <div class="text-5xl mb-4 group-hover:scale-110 transition-transform duration-300">
                        <i class="fas fa-brain"></i>
                    </div>
                    <h5 class="text-xl font-semibold text-gray-800">Neurologist</h5>
                </div>

                <div
                    class="group bg-gray-50 hover:bg-white rounded-2xl shadow-md hover:shadow-xl transition-all p-8 border border-transparent hover:border-gray-200 cursor-pointer">
                    <div class="text-5xl mb-4 group-hover:scale-110 transition-transform duration-300">
                        <i class="fas fa-capsules"></i>
                    </div>
                    <h5 class="text-xl font-semibold text-gray-800">Pharma Pipeline</h5>
                </div>

                <div
                    class="group bg-gray-50 hover:bg-white rounded-2xl shadow-md hover:shadow-xl transition-all p-8 border border-transparent hover:border-gray-200 cursor-pointer">
                    <div class="text-5xl mb-4 group-hover:scale-110 transition-transform duration-300">
                        <i class="fas fa-prescription-bottle-alt"></i>
                    </div>
                    <h5 class="text-xl font-semibold text-gray-800">Pharma Team</h5>
                </div>

                <div
                    class="group bg-gray-50 hover:bg-white rounded-2xl shadow-md hover:shadow-xl transition-all p-8 border border-transparent hover:border-gray-200 cursor-pointer">
                    <div class="text-5xl mb-4 group-hover:scale-110 transition-transform duration-300">
                        <i class="far fa-thumbs-up"></i>
                    </div>
                    <h5 class="text-xl font-semibold text-gray-800">
                        High Quality Treatments
                    </h5>
                </div>
            </div>
        </div>
    </section>

    <!-- About our hospital starts from here  -->
    <section id="about_us" class="bg-[#f9f9f9] py-16">
        <div class="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-8 items-center px-6">

            <!-- Left Image -->
            <div class="w-full h-full">
                <img src="./assets/images/about-us.png" alt="About Our Hospital"
                    class="rounded-2xl shadow-lg w-full h-full object-cover" />
            </div>

            <!-- Right Content -->
            <div>
                <h3 class="text-3xl md:text-4xl font-bold text-gray-800 mb-5">
                    About Our Hospital
                </h3>
                <p class="text-gray-600 leading-relaxed text-justify">
                    The Hospital Management System (HMS) is designed to replace manual, paper-based processes in
                    hospitals. It helps
                    manage patient information, room availability, staff schedules, and patient billing — all in an
                    efficient,
                    cost-effective way that saves time and reduces errors.
                </p>
                <p class="text-gray-600 leading-relaxed mt-4 text-justify">
                    HMS streamlines the acquisition, management, and retrieval of critical hospital data — including
                    patient
                    records, staff details, room assignments, and operation schedules. By automating these processes,
                    HMS enhances
                    accuracy, ensures data integrity, and promotes better use of hospital resources.
                </p>
            </div>
        </div>
    </section>

    <!-- Our gallary starts from here -->
    <!-- Our Gallery Section -->
    <section id="gallery" class="bg-white py-16">
        <div class="max-w-7xl mx-auto px-6">
            <!-- Section Title -->
            <div class="text-center mb-12">
                <h2 class="text-3xl md:text-4xl font-bold text-gray-800 mb-2">Our Gallery</h2>
                <p class="text-gray-600">View Our Gallery</p>
            </div>

            <!-- Filter Buttons -->
            <div class="flex flex-wrap justify-center gap-4 mb-8">
                <button
                    class="filter-btn bg-blue-100 text-blue-700 px-4 py-2 rounded-lg hover:bg-blue-200 active:bg-blue-300"
                    data-filter="all">All</button>
                <button class="filter-btn bg-blue-100 text-blue-700 px-4 py-2 rounded-lg hover:bg-blue-200"
                    data-filter="dental">Dental</button>
                <button class="filter-btn bg-blue-100 text-blue-700 px-4 py-2 rounded-lg hover:bg-blue-200"
                    data-filter="cardiology">Cardiology</button>
                <button class="filter-btn bg-blue-100 text-blue-700 px-4 py-2 rounded-lg hover:bg-blue-200"
                    data-filter="neurology">Neurology</button>
                <button class="filter-btn bg-blue-100 text-blue-700 px-4 py-2 rounded-lg hover:bg-blue-200"
                    data-filter="laboratory">Laboratory</button>
            </div>

            <!-- Gallery Grid -->
            <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
                <!-- Gallery Item -->
                <div class="gallery-item dental">
                    <img src="assets/images/gallery/gallery_01.jpg" alt="Dental"
                        class="w-full h-64 object-cover rounded-xl shadow-md">
                </div>

                <div class="gallery-item cardiology">
                    <img src="assets/images/gallery/gallery_02.jpg" alt="Cardiology"
                        class="w-full h-64 object-cover rounded-xl shadow-md">
                </div>

                <div class="gallery-item dental">
                    <img src="assets/images/gallery/gallery_03.jpg" alt="Dental"
                        class="w-full h-64 object-cover rounded-xl shadow-md">
                </div>

                <div class="gallery-item laboratory">
                    <img src="assets/images/gallery/gallery_04.jpg" alt="Laboratory"
                        class="w-full h-64 object-cover rounded-xl shadow-md">
                </div>

                <div class="gallery-item neurology">
                    <img src="assets/images/gallery/gallery_05.jpg" alt="Neurology"
                        class="w-full h-64 object-cover rounded-xl shadow-md">
                </div>

                <div class="gallery-item neurology">
                    <img src="assets/images/gallery/gallery_06.jpg" alt="Neurology"
                        class="w-full h-64 object-cover rounded-xl shadow-md">
                </div>
            </div>
        </div>
    </section>

    <!-- Contact us starts from here -->
    <section id="contact_us" class="bg-gray-50 py-16">
        <div class="max-w-4xl mx-auto px-6">
            <!-- Section Title -->
            <div class="text-center mb-12">
                <h2 class="text-3xl md:text-4xl font-bold text-gray-800 mb-2">Contact Us</h2>
                <p class="text-gray-600">We’d love to hear from you. Please fill out the form below.</p>
            </div>

            <!-- Contact Form Card -->
            <div class="bg-white shadow-xl rounded-2xl p-8 md:p-12">
                <form method="post" class="space-y-6">

                    <!-- Name -->
                    <div class="flex flex-col md:flex-row md:items-center md:space-x-4">
                        <label class="md:w-1/3 text-gray-700 font-medium mb-1 md:mb-0">Full Name:</label>
                        <input type="text" name="fullname" placeholder="Enter your name" required
                            class="md:w-2/3 px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition" />
                    </div>

                    <!-- Email -->
                    <div class="flex flex-col md:flex-row md:items-center md:space-x-4">
                        <label class="md:w-1/3 text-gray-700 font-medium mb-1 md:mb-0">Email Address:</label>
                        <input type="email" name="emailid" placeholder="Enter your email" required
                            class="md:w-2/3 px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition" />
                    </div>

                    <!-- Mobile -->
                    <div class="flex flex-col md:flex-row md:items-center md:space-x-4">
                        <label class="md:w-1/3 text-gray-700 font-medium mb-1 md:mb-0">Mobile Number:</label>
                        <input type="text" name="mobileno" placeholder="Enter your mobile number" required
                            class="md:w-2/3 px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition" />
                    </div>

                    <!-- Message -->
                    <div class="flex flex-col md:flex-row md:items-start md:space-x-4">
                        <label class="md:w-1/3 text-gray-700 font-medium mb-1 md:mb-0">Message:</label>
                        <textarea name="description" rows="5" placeholder="Enter your message" required
                            class="md:w-2/3 px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition resize-none"></textarea>
                    </div>

                    <!-- Submit Button -->
                    <div class="flex justify-end">
                        <button type="submit" name="submit"
                            class="bg-black text-white font-semibold px-6 py-3 rounded-lg shadow-md w-full">
                            Send Message
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </section>



    <!-- Filtering JS -->
    <script>
    const filterButtons = document.querySelectorAll('.filter-btn');
    const galleryItems = document.querySelectorAll('.gallery-item');

    filterButtons.forEach(btn => {
        btn.addEventListener('click', () => {
            const filter = btn.getAttribute('data-filter');

            galleryItems.forEach(item => {
                if (filter === 'all') {
                    item.classList.remove('hidden');
                } else {
                    if (item.classList.contains(filter)) {
                        item.classList.remove('hidden');
                    } else {
                        item.classList.add('hidden');
                    }
                }
            });

            // Optional: update active button style
            filterButtons.forEach(b => b.classList.remove('bg-blue-300'));
            btn.classList.add('bg-blue-300');
        });
    });
    </script>

</body>

</html>