<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>havenkare-hms</title>

	<!-- Tailwind CSS generated by CLI -->
	<link rel="stylesheet" href="./assets/css/output.css">

	<!-- Custom CSS -->
	<link rel="stylesheet" href="./assets/css/style.css">
</head>

<body>
	<h1 class="bg-amber-100 text-xl test">HavenKare-HMS</h1>
</body>

</html>
